#- name: Add the webupd8team Java PPA
#  apt_repository:
#    repo: ppa:webupd8team/java

#- name: Repository adding for postgresql
#  command: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'

#- name: Add Key
#  command: wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -
- name: Update Repository
  apt:
    update_cache: yes

- name: Install Java 11
  apt:
    name: openjdk-11-jdk
    state: present
    
- name: Create SonarQube system group
  group:
    name: sonar
    state: present

- name: Create SonarQube user
  user:
    name: sonar
    group: sonar
    state: present


- name: Download and archive
  unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.3.zip
    dest: /opt
    owner: sonar
    group: sonar
    remote_src: yes
   

- name: Configure Sonarqube DB username
  lineinfile:
    path: "/opt/sonarqube-7.3/conf/sonar.properties"
    regexp: "^sonar.jdbc.username="
    insertafter: "^#sonar.jdbc.username="
    line: "sonar.jdbc.username=sonar"

- name: Configure Sonarqube DB password
  lineinfile:
    path: "/opt/sonarqube-7.3/conf/sonar.properties"
    regexp: "^sonar.jdbc.password="
    insertafter: "^#sonar.jdbc.password="
    line: "sonar.jdbc.password=P@ssword"

- name: Configure Sonarqube DB connection string
  lineinfile:
    path: "/opt/sonarqube-7.3/conf/sonar.properties"
    regexp: "^sonar.jdbc.url=jdbc:postgresql://localhost/sonar"
    insertafter: "^#sonar.jdbc.url=jdbc:postgresql://localhost/sonar"
    line: "sonar.jdbc.url=jdbc:postgresql://localhost/sonar"

- name: Copy sonar service
  copy:
    src: sonar.service
    dest: /etc/systemd/system
    mode: 0777

- name: Start sonar service
  systemd:
    name: sonar
    state: started
    enabled: true
    daemon_reload: true
 
