#- name: Add the webupd8team Java PPA
#  apt_repository:
#    repo: ppa:webupd8team/java

#- name: Repository adding for postgresql
#  command: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'

#- name: Add Key
#  command: wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -

- name: Install Java 8 & PostgreSQL
  apt:
    name: postgresql
    state: present
    
- name: Install PostgreSQL_Contrib
  apt:
    name: postgresql-contrib
    state: present
  
- name: start and enable postgresql service
  systemd:
    name: postgresql
    state: started
    enabled: true
    daemon_reload: true

# name: Create postgree user for sonarqube
# become: yes
# become_user: postgres
# postgresql_user:
#   name: sonar
#   password: P@ssword
#   encrypted: yes

# name: Create the sonar database
# postgresql_db:
#   name: sonar
#   owner: sonar

- name: Download and archive
  unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.3.zip
    dest: /opt
    remote_src: yes

- name: Configure Sonarqube DB username
  lineinfile:
    path: "/opt/sonarqube-7.3/conf/sonar.properties"
    regexp: "^sonar.jdbc.username="
    insertafter: "^#sonar.jdbc.username="
    line: "sonar.jdbc.username=sonar"

- name: Configure Sonarqube DB password
  lineinfile:
    path: "/opt/sonarqube-7.3/conf/sonar.properties"
    regexp: "^sonar.jdbc.password="
    insertafter: "^#sonar.jdbc.password="
    line: "sonar.jdbc.password=P@ssword"

- name: Configure Sonarqube DB connection string
  lineinfile:
    path: "/opt/sonarqube-7.3/conf/sonar.properties"
    regexp: "^sonar.jdbc.url=jdbc:postgresql://localhost/sonar"
    insertafter: "^#sonar.jdbc.url=jdbc:postgresql://localhost/sonar"
    line: "sonar.jdbc.url=jdbc:postgresql://localhost/sonar"

- name: Copy sonar service
  copy:
    src: sonar.service
    dest: /etc/systemd/system
    mode: 0777

- name: Start sonar service
  systemd:
    name: sonar
    state: started
    enabled: true
    daemon_reload: true
 
